### ISSUE TITLE
مشکل Internal Server Error

### ISSUE THREAD

**Issue by SRNOURI** [hiddify/HiddifyPanel#15]
من از امروز صبح نمیتونم وارد پنل بشم و ارور Internal Server Error میده.

تنظیمات پنل برای انجام آپدیت اتوماتیک و در حالت توسعه بود و آخرین آپدیت انجام شده که کار هم میکرد 7.1.9 بود

چند دفعه اقدام به آپدیت از طریق ترمینال کردم اما متاسفانه ارور میداد و انجام نمیشد. 
ممنون میشم اگر راهنمایی بفرمایید تا بتونم مشکل رو حل کنم.

**Comment by hiddify1** [comment]
./update.sh develop
را زدید؟

**Comment by sajadzi** [comment]
منم همین  مشکل رو دارم
