### ISSUE TITLE
add user id to api callback

### ISSUE THREAD

**Issue by alix1383** [hiddify/HiddifyPanel#16]
خسته نباشید و امیدوارم حالتون خوبه باشه
اگه امکانش هست ایدی کاربرهارو هم اضافه کنید به دیتای بازگشتی api (منظورم uuid نیست)
POST secret/api/v1/user/

**Comment by hiddify1** [comment]
چون id ثابت نیست مثلا با ریستور کردن و غیره تغییر میکنه نمیتونیم بذاریم

**Comment by alix1383** [comment]
برنامه ای برای اضافه کردن قابلیت جدید به api دارین؟

**Comment by hiddify-com** [comment]
قابلیت باید درخواست بشه تا اضافه بشه
