### ISSUE TITLE
Layout issue in mobile

### ISSUE THREAD

**Issue by mehr30na** [hiddify/HiddifyPanel#2]
Please fix the layout on mobile screen. can use full width for the columns maybe. 

![Screenshot 2023-02-09 at 09 35 24](https://user-images.githubusercontent.com/13730082/217759642-69c22143-70c1-482c-8a2f-8762ca9a0479.png)

**Comment by hiddify** [comment]
PR please ;)

**Comment by hiddify** [comment]
what is the error?

**Comment by hiddify** [comment]
خیلی عجیبه
نتونسته اتصال برقرار کنه
یع بار دیگه تست کنید
