### ISSUE TITLE
کانفیگ ریالیتی در حالی که کانفیگ اس اس اچ نیز فعال باشد کار نمیکند.

### ISSUE THREAD

**Issue by TomCat-Hub** [hiddify/HiddifyPanel#22]
در نسخه ی دولوپ وقتی کانفیگ اس اس اچ فعال باشد کانفیگ ریالیتی پینگ میدهد ولی کار نمیکند و وقتی کانفیگ اس اس اچ غیرفعال شود درست میشود.

Panel: 8.0 dev42
Core: Xray
Warp mode: disable

**Comment by hiddify-com** [comment]
به نظر مشکل کانفیلیکت پورت داشتید
رفع شده؟
